name: Run All Lottery Systems

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  trigger-systems:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger LotMix
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/carbosota1/LotMix/actions/workflows/lottery-runner.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger UPDATELOTMIX
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/carbosota1/UPDATELOTMIX/actions/workflows/lottery-runner.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger COMPARE
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/carbosota1/COMPARE/actions/workflows/lottery-runner.yml/dispatches \
          -d '{"ref":"main"}'
